### ISSUE TITLE
./node_modules/web3-eth-accounts/src/scrypt.js Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/starter-kit-gsn#41]
Running the client `npm start` in the `client` directory gives the following warning:
```
Compiled with warnings.

./node_modules/web3-eth-accounts/src/scrypt.js
Critical dependency: the request of a dependency is an expression

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.
```
Checking dependencies:
```
$ npm ls web3-eth-accounts
client@0.1.0 /c/Users/andre/Documents/projects/forum/starter/client
└─┬ web3@1.2.1
  └─┬ web3-eth@1.2.1
    └── web3-eth-accounts@1.2.1
```
The issue is apparently resolved in web3@1.2.2 according to: https://github.com/ethereum/web3.js/issues/3018

**Comment by nivida** [comment]
@abcoathup Yes, this got already fixed and released but be aware to update your package-lock file :)

**Comment by nventuro** [comment]
This should be fixed with #35 and #36. @abcoathup can you check?

**Comment by abcoathup** [comment]
@nventuro 
https://github.com/OpenZeppelin/starter-kit-gsn/blob/master/client/package.json uses web3@1.2.1 so it isn't fixed yet.

**Comment by nventuro** [comment]
Ohh I missed the fact that we have a direct dependency. I think we can safely update it though.
